version: '3.8'

services:
  service1:
    build:
      context: ./service1
      dockerfile: Dockerfile
    container_name: JPT-service-1
    ports:
      - "3501:3501"
    env_file: .env
    environment:
      - PORT=3501
      - SERVICE2_URL=http://service2:3502
      - ATATUS_APP_NAME=JPT-Service-1
    networks:
      - app-network
    depends_on:
      - service2

  service2:
    build:
      context: ./service2
      dockerfile: Dockerfile
    container_name: JPT-service-2
    env_file: .env
    environment:
      - PORT=3502
      - SERVICE_1_URL=http://service1:3501
      - ATATUS_APP_NAME=JPT-Service-2
    ports:
      - "3502:3502"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
